const pantallas={inicio:document.getElementById("pantallaInicio"),registro:document.getElementById("pantallaRegistro"),necesidad:document.getElementById("pantallaNecesidad"),consejos:document.getElementById("pantallaConsejos"),curriculum:document.getElementById("pantallaCurriculum")};
const btnComenzar=document.getElementById("btnComenzar"),registroForm=document.getElementById("registroForm"),opcionesNecesidad=document.querySelectorAll(".opcion-aprendizaje"),listaConsejos=document.getElementById("listaConsejos"),saludoConsejos=document.getElementById("saludoConsejos"),tituloConsejos=document.getElementById("tituloConsejos"),descripcionNecesidad=document.getElementById("descripcionNecesidad"),btnVolverNecesidad=document.getElementById("btnVolverNecesidad"),btnCrearCurriculum=document.getElementById("btnCrearCurriculum"),consejosCv=document.getElementById("consejosCv"),btnVolverConsejos=document.getElementById("btnVolverConsejos"),btnDescargarCv=document.getElementById("btnDescargarCv");
let usuarioActual=null;
const consejos={
Artista:{curriculum:[["Presenta tu perfil artístico","Explica qué tipo de artista eres y qué te diferencia."],["Selecciona tu experiencia","Incluye exposiciones, proyectos, colaboraciones, premios y estudios relevantes."],["Mantén el CV claro","Organiza la información para que sea fácil de leer."],["Adapta tu CV","Destaca la experiencia más relacionada con cada oportunidad."]],portafolio:[["Elige tus mejores obras","Selecciona trabajos que representen tu nivel actual."],["Ordena tus proyectos","Muestra una secuencia que permita entender tu estilo y evolución."],["Explica tus obras","Agrega contexto cuando ayude a comprender el proyecto."],["Cuida la presentación","Utiliza buenas imágenes, títulos claros y navegación sencilla."]],entrevista:[["Habla de tu proceso","Explica cómo desarrollas una idea hasta la obra final."],["Conoce tu portafolio","Debes poder explicar por qué elegiste cada proyecto."],["Explica tu valor","Relaciona tu experiencia con lo que necesita el puesto."],["Prepara ejemplos","Ten proyectos concretos para responder preguntas."]]},
Fotógrafo:{curriculum:[["Define tu especialidad","Indica tu área de fotografía y experiencia relevante."],["Muestra experiencia","Prioriza clientes, proyectos y publicaciones relacionadas."],["Incluye herramientas","Menciona cámaras, iluminación, edición y software que dominas."],["Adapta el CV","Da prioridad a la experiencia relacionada con cada oportunidad."]],portafolio:[["Crea series","Muestra proyectos o series coherentes."],["Selecciona con criterio","Es mejor pocas imágenes muy buenas que muchas repetidas."],["Muestra variedad con intención","La variedad debe demostrar habilidades sin desordenar el portafolio."],["Cuida la calidad","Las imágenes deben verse profesionales."]],entrevista:[["Explica tus decisiones","Cuenta por qué elegiste luz, composición o tratamiento."],["Habla de clientes","Describe cómo entendiste y resolviste sus necesidades."],["Muestra profesionalismo","Explica cómo organizas entregas, tiempos y cambios."],["Lleva ejemplos","Prepara proyectos para hablar de problemas concretos."]]},
Ilustrador:{curriculum:[["Resume tu especialidad","Indica qué tipo de ilustración realizas."],["Destaca proyectos","Prioriza trabajos relacionados con el puesto."],["Incluye herramientas","Menciona programas y técnicas que dominas."],["Mantén una estructura clara","Haz que tu experiencia sea fácil de revisar."]],portafolio:[["Muestra tu estilo","La selección debe permitir reconocer tu estilo."],["Incluye proceso","Bocetos y pruebas demuestran cómo desarrollas ideas."],["Organiza por categorías","Separa tus principales tipos de trabajo."],["Elige pensando en el empleo","Prioriza ejemplos relacionados con el puesto."]],entrevista:[["Explica tu proceso creativo","Describe cómo recibes y desarrollas un encargo."],["Habla de cambios","Explica cómo trabajas con comentarios."],["Defiende tus decisiones","Explica colores, estilos y composiciones."],["Muestra adaptación","Demuestra que puedes adaptarte a distintas necesidades."]]},
Diseñador:{curriculum:[["Enfoca tu perfil","Indica qué área de diseño dominas."],["Destaca resultados","Explica problemas resueltos y resultados cuando puedas."],["Incluye herramientas","Menciona programas que realmente dominas."],["Ordena por relevancia","Coloca primero los proyectos más relacionados."]],portafolio:[["Presenta casos de estudio","Explica problema, proceso, decisiones y resultado."],["Muestra el proceso","Incluye bocetos, pruebas o iteraciones."],["Explica tu rol","Aclara qué parte hiciste tú en proyectos grupales."],["Demuestra criterio","Muestra cómo resolviste problemas, no solo piezas bonitas."]],entrevista:[["Explica decisiones","Habla del razonamiento detrás de tus elecciones."],["Cuenta problemas reales","Prepara ejemplos concretos."],["Habla del equipo","Explica cómo colaboras con otros profesionales."],["Conecta diseño y resultados","Muestra cómo tu trabajo ayudó al proyecto."]]},
Pintor:{curriculum:[["Define tu perfil","Indica tipo de pintura y técnicas principales."],["Incluye exposiciones","Destaca muestras, encargos, colaboraciones y proyectos."],["Menciona técnicas","Incluye óleo, acrílico, acuarela, muralismo u otras."],["Adapta tu presentación","Destaca experiencia relacionada con la oportunidad."]],portafolio:[["Selecciona una colección","Construye una selección coherente."],["Fotografía bien tus obras","La calidad de las fotos influye en la percepción del trabajo."],["Incluye datos","Título, técnica, dimensiones y año pueden aportar contexto."],["Muestra evolución","Puedes mostrar el desarrollo de tu propuesta."]],entrevista:[["Explica tu lenguaje visual","Cuenta ideas, temas o referencias de tu trabajo."],["Habla de tu técnica","Explica cómo desarrollas una obra."],["Relaciona tu experiencia","Muestra cómo tu disciplina aporta al puesto."],["Prepara obras concretas","Elige piezas que puedas explicar con claridad."]]},
Animador:{curriculum:[["Presenta tu especialidad","Indica si trabajas en 2D, 3D, motion graphics, personajes o VFX."],["Destaca proyectos","Prioriza trabajos relacionados con animación."],["Incluye software","Menciona las herramientas que dominas."],["Explica tu rol","Aclara exactamente qué parte realizaste."]],portafolio:[["Crea un reel","Un reel breve y bien seleccionado muestra rápidamente tu nivel."],["Muestra proceso","Incluye storyboards, layouts o pruebas cuando aporten valor."],["Selecciona por objetivo","Prioriza trabajos relacionados con el empleo buscado."],["Cuida el ritmo","Coloca tus trabajos más fuertes al principio."]],entrevista:[["Explica tu proceso","Habla desde idea y storyboard hasta resultado final."],["Habla de producción","Explica cómo organizas tiempos, archivos y entregas."],["Muestra colaboración","Demuestra que sabes trabajar con otros roles."],["Defiende tus decisiones","Explica movimientos, tiempos y recursos visuales."]]},
Otro:{curriculum:[["Define tu perfil","Explica qué haces y qué oportunidad buscas."],["Prioriza experiencia","Coloca primero lo más relacionado con el empleo."],["Incluye habilidades","Selecciona las realmente relevantes."],["Adapta tu CV","No uses exactamente el mismo CV para todo."]],portafolio:[["Selecciona lo mejor","Muestra proyectos que representen tus habilidades."],["Organiza tu trabajo","Usa categorías y títulos claros."],["Explica tu participación","Aclara qué hiciste tú."],["Piensa en el empleador","Selecciona ejemplos útiles para el puesto."]],entrevista:[["Conoce tus proyectos","Debes poder explicar qué hiciste y qué aprendiste."],["Prepara ejemplos","Ten historias concretas de problemas y resultados."],["Explica tu aporte","Relaciona tus habilidades con la necesidad del puesto."],["Practica","Ensaya respuestas claras."]]}
};
function cambiarPantalla(actual,siguiente){actual.classList.add("saliendo");setTimeout(()=>{actual.classList.add("oculta");actual.classList.remove("activa","saliendo");siguiente.classList.remove("oculta");siguiente.classList.add("entrando");window.scrollTo({top:0,behavior:"smooth"});setTimeout(()=>siguiente.classList.remove("entrando"),700)},600)}
btnComenzar.addEventListener("click",()=>cambiarPantalla(pantallas.inicio,pantallas.registro));
registroForm.addEventListener("submit",e=>{e.preventDefault();const nombre=document.getElementById("nombre").value.trim(),correo=document.getElementById("correo").value.trim(),telefono=document.getElementById("telefono").value.trim(),profesion=document.getElementById("profesion").value;if(!nombre||!correo||!telefono||!profesion){document.getElementById("errorRegistro").textContent="Completa todos los campos para continuar.";return}usuarioActual={nombre,correo,telefono,profesion};localStorage.setItem("usuario",JSON.stringify(usuarioActual));cambiarPantalla(pantallas.registro,pantallas.necesidad)});
opcionesNecesidad.forEach(op=>op.addEventListener("click",()=>{if(!usuarioActual)return;const necesidad=op.dataset.necesidad;mostrarConsejos(usuarioActual,necesidad);cambiarPantalla(pantallas.necesidad,pantallas.consejos)}));
function mostrarConsejos(usuario,necesidad){const datos=(consejos[usuario.profesion]||consejos.Otro)[necesidad],nombres={curriculum:"Currículum",portafolio:"Portafolio",entrevista:"Entrevistas"};saludoConsejos.textContent=`Hola, ${usuario.nombre}. Eres ${usuario.profesion}.`;tituloConsejos.textContent=`Cómo mejorar tu ${nombres[necesidad]}`;descripcionNecesidad.textContent=necesidad==="curriculum"?"Consejos para presentar mejor tu experiencia profesional.":necesidad==="portafolio"?"Consejos para mostrar tus mejores trabajos de acuerdo con tu profesión.":"Consejos para explicar tu experiencia y destacar en una entrevista.";listaConsejos.innerHTML="";datos.forEach(i=>{const a=document.createElement("article");a.className="consejo";a.innerHTML=`<h3>${i[0]}</h3><p>${i[1]}</p>`;listaConsejos.appendChild(a)});btnCrearCurriculum.classList.toggle("oculto",necesidad!=="curriculum")}
function mostrarAyudaCurriculum(){consejosCv.innerHTML="";(consejos[usuarioActual.profesion]||consejos.Otro).curriculum.forEach(i=>{const d=document.createElement("div");d.className="ayuda-item";d.innerHTML=`<strong>${i[0]}</strong><p>${i[1]}</p>`;consejosCv.appendChild(d)})}
btnCrearCurriculum.addEventListener("click",()=>{mostrarAyudaCurriculum();document.getElementById("cvNombre").value=usuarioActual.nombre;document.getElementById("cvProfesion").value=usuarioActual.profesion;document.getElementById("cvContacto").value=usuarioActual.correo+" · "+usuarioActual.telefono;actualizarVistaPrevia();cambiarPantalla(pantallas.consejos,pantallas.curriculum)});
btnVolverNecesidad.addEventListener("click",()=>cambiarPantalla(pantallas.consejos,pantallas.necesidad));btnVolverConsejos.addEventListener("click",()=>cambiarPantalla(pantallas.curriculum,pantallas.consejos));
function v(id,fb){return document.getElementById(id).value.trim()||fb}function actualizarVistaPrevia(){document.getElementById("previewNombre").textContent=v("cvNombre","Tu nombre");document.getElementById("previewProfesion").textContent=v("cvProfesion","Tu profesión");document.getElementById("previewContacto").textContent=v("cvContacto","Tu contacto");document.getElementById("previewPerfil").textContent=v("cvPerfil","Tu perfil aparecerá aquí.");document.getElementById("previewExperiencia").textContent=v("cvExperiencia","Tu experiencia aparecerá aquí.");document.getElementById("previewEducacion").textContent=v("cvEducacion","Tu educación aparecerá aquí.");document.getElementById("previewHabilidades").textContent=v("cvHabilidades","Tus habilidades aparecerán aquí.")}
["cvNombre","cvProfesion","cvContacto","cvPerfil","cvExperiencia","cvEducacion","cvHabilidades"].forEach(id=>document.getElementById(id).addEventListener("input",actualizarVistaPrevia));
btnDescargarCv.addEventListener("click",()=>{actualizarVistaPrevia();window.print()});
const guardado=localStorage.getItem("usuario");if(guardado){try{usuarioActual=JSON.parse(guardado);document.getElementById("nombre").value=usuarioActual.nombre||"";document.getElementById("correo").value=usuarioActual.correo||"";document.getElementById("telefono").value=usuarioActual.telefono||"";document.getElementById("profesion").value=usuarioActual.profesion||""}catch(e){localStorage.removeItem("usuario")}}
